Support for wtns calc memSize option
iden3/snarkjs pull request #517
Opened 2024-08-16 01:47 UTC by OBrezhniev

Use circom_runtime which supports memSize option. 
Passing options in wtns debug too.

2024-09-03 14:13 UTC, Kolezhniuk requested changes

2024-09-03 14:13 UTC, Kolezhniuk commented on src/wtns_debug.js
> +    wcOps.sanityCheck = true;
`const wcOps = {... options, sanityCheck: true};`

2024-09-07 15:31 UTC, OBrezhniev commented on src/wtns_debug.js
> +    const w = await wc.calculateWitness(input, true);
It sets sanityCheck param to true.

2024-09-07 15:45 UTC, OBrezhniev commented on package.json
> +    "circom_runtime": "iden3/circom_runtime#6d4843929b61baba03be8090b094946e54717192",
@Kolezhniuk, 

Yes, please review iden3/circom_runtime#111

2024-09-09 07:37 UTC, Kolezhniuk submitted a review, later dismissed

2024-09-10 08:17 UTC, Kolezhniuk submitted a review, later dismissed

2024-10-07 19:14 UTC, rrrliu commented
hey @Kolezhniuk @OBrezhniev 👋 checking in on this here, are we good to merge here?

this change would be super helpful for our app, which needs the memorySize option to ensure proving doesn't crash on mobile browsers :)

2024-10-09 09:00 UTC, OBrezhniev commented
Yes, I hope a final review and release would happen next week.

2024-10-16 05:58 UTC, Kolezhniuk submitted a review, later dismissed

2024-10-16 15:25 UTC, Kolezhniuk approved these changes

2024-10-18 01:24 UTC, rrrliu commented
thanks for the review @Kolezhniuk -- excited for the release!

2024-10-18 09:09 UTC, merged

2024-10-18 10:24 UTC, OBrezhniev commented
Hi @rrrliu , it's merged and released.